Add arm64 support and GitHub action
leodotcloud/swiss-army-knife pull request #31
Opened 2024-09-06 10:54 UTC by xshadowlegendx

2024-09-12 13:16 UTC, xshadowlegendx commented
hello @leodotcloud, please tell me if you need any changes and have any feedback on the pr, thanks you

2025-09-12 07:20 UTC, suryatejaboorlu reviewed
I did test this is my raspberry PI which is arm64 and it worked fine for me.

2025-09-13 12:29 UTC, leodotcloud requested changes
@xshadowlegendx can you please rebase your changes on top of main branch instead of merging main into your branch? We try to keep the commit history linear, hence asking.

2025-09-14 05:25 UTC, xshadowlegendx commented
> @xshadowlegendx can you please rebase your changes on top of main branch instead of merging main into your branch? We try to keep the commit history linear, hence asking.

got it, will rebase it instead

2025-09-14 16:31 UTC, xshadowlegendx commented on .github/workflows/build-app.yml
> +          registry: ghcr.io
hello @leodotcloud, i have change to use dockerhub instead and  have `DOCKERHUB_USER` and `IMAGE_REF` as github repo variable and `DOCKERHUB_TOKEN` as github repo secret for authenticating to dockerhub

2025-09-14 18:19 UTC, leodotcloud requested changes

2025-09-15 03:24 UTC, xshadowlegendx commented on .github/workflows/build-app.yml
> +        required: true
yes it is possible, let me make an update on that

2025-09-15 03:31 UTC, xshadowlegendx commented on .github/workflows/build.yml
> +    secrets: inherit
yes we should do a build and push only on release and only build on pr and also not passing secret into it, I will make an update to this also

2025-09-18 11:32 UTC, leodotcloud approved these changes

2025-09-18 11:33 UTC, merged

2025-09-18 11:46 UTC, leodotcloud commented
@xshadowlegendx I have merged your PR, but the build is failing: https://github.com/leodotcloud/swiss-army-knife/actions/runs/17827484673/job/50684316111

2025-10-02 15:14 UTC, xshadowlegendx commented
hello @leodotcloud, sorry for the late reply, you have to set `IMAGE_REF` in github `Actions secrets and variables` like so  `leodotcloud/swiss-army-knife`, from the logs it is missing that

2025-10-04 04:13 UTC, leodotcloud commented
That worked @xshadowlegendx. Thanks!